[flake8]
max-line-length=89
ignore =
    # E402: Import not at top of file ...
    E402,
    # W503 line break before binary operator is actually best-practise nowadays https://www.flake8rules.com/rules/W504.html
    W503,
